name = "End Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36a68bb91bdbd62794c9c7641d9ac4195a580f4e2434beb5b65998ca6fcff9fb"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
