name = "End Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27eddf5e5c442d362e03ce236dffbc79a30120208d14a78cffb010f77de45571"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
