name = "End Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffd8c30b39cca0f7a8a957464a6f5215291b49bf21cbf12348122f0797cc70b7"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
