name = "End Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1512c453b55e3f8b001f80bfd28c785baedccb078106fc16ac413fbfafec3c97"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
