name = "End Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78298e752233f8b3e594a9f9b0cc6a9c0b908d15e664c8252329f8393c9b7d16"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
