name = "End Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75f8dd0bbc8de3d6d10a88bb3026f1872594e9ef9bf003102ecf31d65c56ea9e"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
