name = "End Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cf3ba4d083a5e073e2e26d0cf688e2345eef995c497dcc45194a43d33dcc3f9"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
